apply plugin: 'com.android.application'

android {
    compileSdk 35
    defaultConfig {
        applicationId "org.bibledit.android"
        minSdkVersion 22
        targetSdkVersion 35
        versionCode 171
        versionName "5.1.037"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++20"
            }
        }
        ndk {
            debugSymbolLevel = 'FULL'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            ndk {
                debugSymbolLevel = 'FULL'
            }
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version = "4.1.2"
        }
    }
    namespace = 'org.bibledit.android'
    ndkVersion '29.0.14206865'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.4.2'
}
